version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - network.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - node.name=cluster1-node1
      - xpack.license.self_generated.type=basic
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2048m -Xmx2048m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks:
      - esnet

  kibana:
    image: kibana:8.5.3
    container_name: kibana
    environment:
     ELASTICSEARCH_HOSTS: http://elasticsearch:9200
     SERVER_HOSTS: 0.0.0.0
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch

networks:
  esnet:

