services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse
    volumes:
      - ${PWD}/config/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/config/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/data/:/var/lib/clickhouse
    ports:
    - "8123:8123"
    - "9000:9000"
