services:
  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - "8001:80"
      - "8002:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  # example usage:
  # nginx:
  #   image: "nginx:alpine"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.ainyava.rule=Host(`ainyava.localhost`)"
  #     - "traefik.http.routers.ainyava.entrypoints=web"
  #     - "traefik.http.services.ainyava.loadbalancer.server.scheme=h2c"
