version: "3.9"
networks:
  selenium-grid:
    name: selenium-grid
services:
  hub:
    image: selenium/hub
    expose:
      - 4444
    networks:
      - selenium-grid
  chrome:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5900:5900
    depends_on:
      - hub
    networks:
      - selenium-grid
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
